# Generated by Django 3.0.3 on 2020-02-22 22:54

import datetime
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название хакатона', max_length=200)),
                ('small_description', models.CharField(help_text='Введите краткое описание хакатона', max_length=200)),
                ('hackText', djrichtextfield.models.RichTextField(help_text='Введите полностью условия хакатона')),
                ('pub_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(default=' ', upload_to='')),
                ('filter', models.CharField(choices=[('online', 'онлайн'), ('offline', 'оффлайн')], default='online', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название мероприятия', max_length=200)),
                ('small_description', models.CharField(help_text='Введите краткое описание мероприятия', max_length=200)),
                ('hackText', djrichtextfield.models.RichTextField(help_text='Введите полностью условия хакатона')),
                ('pub_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(default=' ', upload_to='')),
                ('filter', models.CharField(choices=[('met', 'митап'), ('run', 'забег'), ('conf', 'конференция')], default='met', max_length=20)),
            ],
        ),
    ]
