# Generated by Django 3.0.4 on 2020-03-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
