# Generated by Django 3.0.4 on 2020-03-25 14:43

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('reg', '0005_uzer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzer',
            name='department',
        ),
        migrations.AddField(
            model_name='hack',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='uzer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uzer',
            name='friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uzer',
            name='info',
            field=models.CharField(default=' ', help_text='Введите информацию о себе', max_length=200),
        ),
        migrations.AddField(
            model_name='uzer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uzer',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
