# Generated by Django 3.0.4 on 2020-03-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_auto_20200328_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzer',
            name='age',
            field=models.DateField(blank=True),
        ),
    ]
