# Generated by Django 3.0.4 on 2020-03-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0008_auto_20200328_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzer',
            name='age',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
