# Generated by Django 3.0.4 on 2020-03-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0009_auto_20200328_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzer',
            old_name='friends',
            new_name='Friends',
        ),
        migrations.RenameField(
            model_name='uzer',
            old_name='info',
            new_name='Info',
        ),
        migrations.RenameField(
            model_name='uzer',
            old_name='place',
            new_name='Place',
        ),
        migrations.RenameField(
            model_name='uzer',
            old_name='rating',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='uzer',
            old_name='school',
            new_name='School',
        ),
        migrations.RenameField(
            model_name='uzer',
            old_name='skills',
            new_name='Skills',
        ),
        migrations.RenameField(
            model_name='uzer',
            old_name='uni',
            new_name='Uni',
        ),
        migrations.RenameField(
            model_name='uzer',
            old_name='uniEnd',
            new_name='UniEnd',
        ),
        migrations.RenameField(
            model_name='uzer',
            old_name='visits',
            new_name='Visits',
        ),
        migrations.RemoveField(
            model_name='uzer',
            name='age',
        ),
        migrations.AddField(
            model_name='uzer',
            name='BirthDay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
