# Generated by Django 3.0.4 on 2020-04-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0010_auto_20200328_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzer',
            name='avatar',
            field=models.ImageField(default=' ', upload_to=''),
        ),
    ]
