# Generated by Django 3.0.4 on 2020-04-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0011_uzer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzer',
            name='avatar',
            field=models.ImageField(default=' ', upload_to='profile/'),
        ),
    ]
