# Generated by Django 3.0.4 on 2020-04-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('reg', '0013_auto_20200424_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='EventsModel',
        ),
    ]
