# Generated by Django 3.0.4 on 2020-04-24 14:12

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0014_auto_20200424_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsmodel',
            name='hackText',
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='Text',
            field=djrichtextfield.models.RichTextField(default='', help_text='Введите полностью условия'),
        ),
        migrations.AlterField(
            model_name='eventsmodel',
            name='small_description',
            field=models.CharField(help_text='Введите краткое описание', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventsmodel',
            name='title',
            field=models.CharField(help_text='Введите название', max_length=200),
        ),
    ]
