# Generated by Django 3.0.4 on 2020-04-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0020_auto_20200427_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
