# Generated by Django 3.0.4 on 2020-05-07 12:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0021_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmodel',
            name='Text',
            field=tinymce.models.HTMLField(default='', help_text='Введите полностью условия'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=tinymce.models.HTMLField(default='', help_text='Введите полностью условия'),
        ),
    ]
