# Generated by Django 3.0.4 on 2020-05-07 12:34

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0022_auto_20200507_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmodel',
            name='Text',
            field=djrichtextfield.models.RichTextField(default='', help_text='Введите полностью условия'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=djrichtextfield.models.RichTextField(default='', help_text='Введите полностью условия'),
        ),
    ]
