# Generated by Django 3.0.4 on 2020-05-10 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0023_auto_20200507_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsmodel',
            old_name='pub_date',
            new_name='event_end',
        ),
        migrations.AddField(
            model_name='eventsmodel',
            name='event_start',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
