# Generated by Django 3.0.4 on 2020-05-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0025_remove_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmodel',
            name='Text',
            field=models.TextField(default='', help_text='Введите полностью условия'),
        ),
        migrations.AlterField(
            model_name='uzer',
            name='Info',
            field=models.CharField(default=' ', help_text='Введите информацию о себе', max_length=300),
        ),
        migrations.AlterField(
            model_name='uzer',
            name='Place',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='uzer',
            name='School',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='uzer',
            name='Uni',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='uzer',
            name='UniEnd',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
